#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

require_installer package-manager
require_installer node
require_installer git
require_installer zsh

brew_cask_install rectangle
brew_install direnv
brew_install autojump