#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

use_rbenv
require_installer package-manager
require_installer zsh
require_installer ruby
require_installer node
require_installer git

brew_cask_install rectangle
brew_install direnv
brew_install autojump
