#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

symlink_dotfile bashrc ~/.bashrc
symlink_dotfile bash_profile ~/.bash_profile

require_installer package-manager
require_installer node
require_installer git
require_installer terminal

brew_install direnv
brew_install autojump
brew_install exa
