#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if [ ! -d ~/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
fi

if [ ! -f $HOME/.fzf.bash ]; then
  ~/.fzf/install
  fi


