#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer ruby

function source_nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
}

function install_nvm() {
  if [ ! -d ~/.nvm ]; then
    curl -o- \
      https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

    source_nvm

    nvm install stable
  fi
}

install_nvm
source_nvm
brew_install yarn
