#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if test ! $(command -v brew); then
    echo "Installing homebrew"

    ruby -e "$(curl -fsSL \
      https://raw.githubusercontent.com/Homebrew/install/HEAD/install)"

    brew update
  fi

echo "Setting up Homebrew..."
