#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if test ! $(command -v brew); then
    echo "Installing homebrew"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"

    brew update
  fi

echo "Setting up Homebrew..."
